language: elixir
elixir:
  - 1.5.0
otp_release:
  - 20.0
sudo: false
env:
  - MIX_ENV=test
script:
  - mix do compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
